# Generated by Django 2.1 on 2020-12-07 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnslookup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchedDomains',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
